apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-0qkk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0073-tenant/tkrw-pr714-0075-0073-app/devfile-sample-0qkk@sha256:54cd7d07fc5a9c73f0c2e3c65425ac874c563521529631f93081431adc2c63a9
        name: my-nodejs
        resources: {}
status: {}
